### ISSUE TITLE
Support roles

### ISSUE THREAD

**Issue by migo315** [bestit/flagception-bundle#30]
Add one standard role provider for active features.

Example:
```
# For one role
constraint: has_role('ROLE_ADMIN')

# For multiple roles
constraint: "has_role('ROLE_ADMIN') or has_role('ROLE_MOD')"
```

**Comment by migo315** [comment]
Will be implemented in the next version. However, not with the expression language but as a separate field, as in the symfony security component.

```
flagception:
    features:      
        # Only one role
        feature_123:
            roles: ROLE_ADMIN
            
        # Multiple roles
        feature_456:
            roles: ROLE_ADMIN,ROLE_MOD
        
        # Multiple roles (alternative formatting)
        feature_789:
            roles:
                - ROLE_ADMIN
                - ROLE_MOD
```
