### ISSUE TITLE
Cookie feature name

### ISSUE THREAD

**Issue by migo315** [bestit/flagception-bundle#41]
Currently, you enable or disable a feature by cookie with the feature name:

In this configuration, the cookie must contain "feature_123".
```
# config.yml
flagception:
    features:      
    
        # Activatable via cookie
        feature_123:
            cookie: true
```

It should be possible to specify an alternative name for the feature in the cookie:
```
# config.yml
flagception:
    features:      
    
        # Activatable via cookie
        feature_123:
            cookie: MY_SECRET_COOKIE_NAME
```

This new config allow instead of "true / false" a string with a name, which is then expected as cookie content. If you continue to pass only "true", as before, the feature name is taken.
