### ISSUE TITLE
[Feature Request] Priority customization

### ISSUE THREAD

**Issue by GrosTon1** [bestit/flagception-bundle#53]
There is currently no way (or none that the docs shows) to to prioritize cookies over anything else. This stop from debugging when having the feature toggled off and enabling it with cookies.

**Comment by migo315** [comment]
Thanks for the hint - the priority isn't documented. You can set a priority for each activator (the higher the number, the earlier an activator is executed). For example:

```yml
# config.yml

flagception:
    features:      
        feature_123:
            default: false
   
    activators:
        # Cookie settings         
        cookie:
            priority: 300
            enable: true
            name: 'flagception'
            separator: ','
```

The default priorities are:
- ConstraintActivator: 210
- ContentfulActivator: 150
- CookieActivator: 200
- DatabaseActivator: 220
- EnvironmentActivator: 230
- ArrayActivator: 255 (this is used for the "default" field)


But that isn't your problem. The feature manager iterate through all activators and check the state with the `isActive` method until one activator returns true. If an activator returns true, no further activators will be requested. This means, if you have toggled off a feature but enabled it with a cookie, the feature should be activated for you - regardless if the CookieActivator will be executed before or after all other activators. 

Do you have enabled the cookie activator? The activator is disabled by default (due security reasons). See https://github.com/bestit/flagception-bundle/blob/master/docs/cookie.md

**Comment by GrosTon1** [comment]
After looking at flagception (and not flagception-bundle), I saw that the cookie activator is looking at $this->features, so it is not compatible with database but only with features declared in the yaml saldy :/
That's why I tought the priority wasn't effective, but it's because the features declared in the database can't be activated trough cookies.

**Comment by migo315** [comment]
You are right. I normally recommended to declare all feature flags in your config.yml (all disabled) an then activate your features via database, contentful or something else. 

But I think this isn't "update to date" anymore. The config.yml should be optional and not mandatory for the CookieActivator. I will update the CookieActivator until sunday - so that you can use it for all your features, regardless if you set your features in you config.yml, database or whatever.

**Comment by migo315** [comment]
I've created a branch. There you can change the behaviour for the cookie activator. Currently, only features defined in your config.yml are allowed for cookie toggling (whitelist). In my branch you can set the mode as "blacklist". Then are all features allowed for cookie toggling unless you explicitly disable it for that.

```yml
# config.yml

flagception:
    features:      
        # No features defined here because you are only using database

    # Cookie settings         
    cookie:
        enable: true
        mode: 'blacklist'

    database:
        # Your database settings
```

I will test this branch today / tomorrow and then merge and release it.

**Comment by migo315** [comment]
Tests are fine. Released under 3.2.0. So just update flagception to version ^3.2 and set the "mode" to "blacklist":

```yml
# config.yml

flagception:
    features:      
        # No features defined here because you are only using database

    # Cookie settings         
    cookie:
        enable: true
        mode: 'blacklist'

    database:
        # Your database settings
```

Then should everything work as you expect.
