### ISSUE TITLE
[Refactor] Cookie Activator

### ISSUE THREAD

**Issue by migo315** [bestit/flagception-bundle#57]
The new Flagception Bundle 4.0 will work without the shared "features" tree. Each activator has his own feature tree (if needed) or work without them.

The new "CookieActivator" will replace the old one. It designed to work without a feature list. So all features in your cookie will be enabled:

```yml
# config.yml

flagception:   
    activators:    
        cookie:
            enable: true
        database:
            // ...
        contentful:
            // ...
        memory:
            // ...
```

But you can optionally set a blacklist or whitelist:

```yml
# config.yml

flagception:   
    activators:    
        cookie:
            enable: true
            mode: 'blacklist' (or 'whitelist')
            features:
                 - 'feature_foo'
                 - 'feature_newletter_(.*)' # Can by a regex too 
        database:
            // ...
        contentful:
            // ...
        memory:
            // ...
```
