### ISSUE TITLE
[Refactor] Environment Activator

### ISSUE THREAD

**Issue by migo315** [bestit/flagception-bundle#58]
The new Flagception Bundle 4.0 will work without the shared "features" tree. Each activator has his own feature tree (if needed) or work without them.

The new "EnvironmentActivator" will replace the old one. It designed to work without a feature list. So all features which are defined as environment variables will be used. You do not have to set it in your config.yml:

```yml
# config.yml

flagception:   
    activators:    
        environment:
            enable: true
        database:
            // ...
        contentful:
            // ...
        memory:
            // ...
```

But you can optionally set a blacklist or whitelist:

```yml
# config.yml

flagception:   
    activators:    
        environment:
            enable: true
            mode: 'blacklist' # (or 'whitelist')
            features:
                 - 'feature_foo'
                 - 'feature_newletter_(.*)' # Can be a regex too 
        database:
            // ...
        contentful:
            // ...
        memory:
            // ...
```
